"""
FLUX Decomposer - Code → Natural Language → FLUX Vocabulary

The killer feature. Takes any Python library (or source code) and decomposes
it into .fluxvocab patterns that any agent can use through natural language.

Pipeline:
  source code → function signatures + logic → natural language patterns → .fluxvocab

This makes any library a vocabulary. Any agent can learn it. Any user can share it.

Usage:
    from flux.open_interp.decomposer import Decomposer

    d = Decomposer()

    # Decompose a module
    vocab = d.decompose_module("math")
    vocab.save("vocabularies/custom/math.fluxvocab")

    # Decompose a single file
    vocab = d.decompose_file("my_lib.py")

    # Decompose and use immediately
    vocab = d.decompose_module("statistics")
    interp = OpenFluxInterpreter()
    interp.load_vocabulary(vocab)
    result = interp.run("mean of 1 2 3 4 5")
"""

import ast
import inspect
import importlib
import textwrap
import re
import os
import json
from typing import Optional, List, Dict, Tuple, Any
from dataclasses import dataclass, field


# ─── FLUX-ese Grammar ──────────────────────────────────────────────────────
#
# FLUX-ese is a controlled natural language for expressing computations.
# Like legalese for law, FLUX-ese for computation.
#
# Core patterns:
#   "compute <operation> of <values>"       → arithmetic
#   "find <property> in <data>"             → search/filter
#   "sort <data> by <criterion>"            → ordering
#   "check if <condition>"                  → validation
#   "convert <value> to <type>"             → transformation
#   "generate <thing> from <source>"        → creation
#   "count <items> where <condition>"       → aggregation
#   "combine <a> and <b> using <method>"    → composition


@dataclass
class FunctionProfile:
    """Profile of a function extracted from source code."""
    name: str
    module: str
    args: List[Dict[str, Any]] = field(default_factory=list)
    returns: str = "unknown"
    docstring: str = ""
    body_summary: str = ""
    complexity: str = "simple"  # simple, moderate, complex
    category: str = ""  # math, data, string, io, etc.
    natural_patterns: List[str] = field(default_factory=list)
    flux_asm: str = ""
    tags: List[str] = field(default_factory=list)


@dataclass
class DecomposedVocabulary:
    """A vocabulary decomposed from source code."""
    module_name: str
    entries: List[Dict] = field(default_factory=list)
    metadata: Dict = field(default_factory=dict)

    def save(self, path: str):
        """Save as .fluxvocab file."""
        os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
        with open(path, 'w') as f:
            f.write(self._to_fluxvocab())

    def _to_fluxvocab(self) -> str:
        """Generate .fluxvocab format."""
        parts = []
        parts.append(f"# Vocabulary decomposed from: {self.module_name}")
        parts.append(f"# Functions: {len(self.entries)}")
        parts.append(f"# Generated by FLUX Decomposer\n")

        for entry in self.entries:
            parts.append("---")
            parts.append(f'pattern: "{entry["pattern"]}"')
            parts.append(f'expand: |')
            for line in entry.get("assembly", "MOVI R0, 0\nHALT").strip().split('\n'):
                parts.append(f'    {line}')
            parts.append(f'result: R{entry.get("result_reg", 0)}')
            parts.append(f'name: {entry["name"]}')
            parts.append(f'description: {entry.get("description", "")}')
            if entry.get("tags"):
                parts.append(f'tags: {", ".join(entry["tags"])}')
            parts.append('')

        return '\n'.join(parts)

    @property
    def path(self):
        return f"vocabularies/{self.module_name}"


class Decomposer:
    """
    Decomposes Python source code into FLUX vocabulary patterns.

    The decomposer reads function signatures, docstrings, and logic,
    then generates natural language patterns in FLUX-ese that map
    to FLUX bytecode.
    """

    def __init__(self):
        self.profiles: List[FunctionProfile] = []
        self._type_map = {
            int: "number", float: "number", str: "text",
            list: "list", dict: "map", bool: "boolean",
            tuple: "sequence", set: "collection",
        }
        self._math_ops = {
            'add': '+', 'sub': '-', 'mul': '*', 'truediv': '/',
            'floordiv': '//', 'mod': '%', 'pow': '**',
        }

    def decompose_module(self, module_name: str) -> DecomposedVocabulary:
        """Decompose a Python module into vocabulary patterns."""
        try:
            mod = importlib.import_module(module_name)
        except ImportError:
            raise ValueError(f"Cannot import module: {module_name}")

        entries = []

        for name in sorted(dir(mod)):
            if name.startswith('_'):
                continue
            obj = getattr(mod, name)

            if callable(obj) and not isinstance(obj, type):
                try:
                    profile = self._profile_function(name, obj, module_name)
                    if profile:
                        vocab_entries = self._profile_to_vocab(profile)
                        if vocab_entries:
                            entries.extend(vocab_entries)
                            self.profiles.append(profile)
                except Exception:
                    continue

        return DecomposedVocabulary(
            module_name=module_name,
            entries=entries,
            metadata={
                "functions_analyzed": len(self.profiles),
                "patterns_generated": len(entries),
            }
        )

    def decompose_file(self, filepath: str) -> DecomposedVocabulary:
        """Decompose a Python source file into vocabulary patterns."""
        with open(filepath, 'r') as f:
            source = f.read()

        tree = ast.parse(source)
        entries = []
        module_name = os.path.splitext(os.path.basename(filepath))[0]

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
                profile = self._profile_ast_function(node, module_name, source)
                if profile:
                    vocab_entries = self._profile_to_vocab(profile)
                    entries.extend(vocab_entries)
                    self.profiles.append(profile)

        return DecomposedVocabulary(
            module_name=module_name,
            entries=entries,
            metadata={
                "functions_analyzed": len(self.profiles),
                "patterns_generated": len(entries),
            }
        )

    def decompose_string(self, code: str, module_name: str = "inline") -> DecomposedVocabulary:
        """Decompose a code string into vocabulary patterns."""
        tree = ast.parse(code)
        entries = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef) and not node.name.startswith('_'):
                profile = self._profile_ast_function(node, module_name, code)
                if profile:
                    vocab_entries = self._profile_to_vocab(profile)
                    entries.extend(vocab_entries)
                    self.profiles.append(profile)

        return DecomposedVocabulary(
            module_name=module_name,
            entries=entries,
        )

    def _profile_function(self, name: str, func: callable, module: str) -> Optional[FunctionProfile]:
        """Profile a live function."""
        try:
            sig = inspect.signature(func)
        except (ValueError, TypeError):
            # Built-in function - try to infer from docs and name
            doc = inspect.getdoc(func) or ""
            return self._profile_builtin(name, func, module, doc)

        args = []
        for pname, param in sig.parameters.items():
            # Skip *args/**kwargs for pattern matching
            if param.kind in (inspect.Parameter.VAR_POSITIONAL, inspect.Parameter.VAR_KEYWORD):
                continue
            ptype = "any"
            if param.annotation != inspect.Parameter.empty:
                ptype = self._type_map.get(param.annotation, str(param.annotation))
            default = None if param.default == inspect.Parameter.empty else param.default
            args.append({"name": pname, "type": ptype, "default": default})

        ret_type = "any"
        if sig.return_annotation != inspect.Signature.empty:
            ret_type = self._type_map.get(sig.return_annotation, str(sig.return_annotation))

        doc = inspect.getdoc(func) or ""

        return FunctionProfile(
            name=name,
            module=module,
            args=args,
            returns=ret_type,
            docstring=doc,
            category=self._categorize(name, doc, args),
        )

    def _profile_builtin(self, name: str, func: callable, module: str, doc: str) -> Optional[FunctionProfile]:
        """Profile a built-in function using docs and name inference."""
        # Parse docstring for parameter info
        # Common patterns: "func(x, /, ...)" or "func(x, y, /, ...)"
        args = []

        # Try to extract params from docstring
        first_line = doc.split('\n')[0] if doc else ""
        # Pattern: name(x, y) or name(x, y, /)
        param_match = re.search(rf'{re.escape(name)}\(([^)]*)\)', first_line)
        if param_match:
            param_str = param_match.group(1)
            for p in param_str.split(','):
                p = p.strip().rstrip('/')
                p = p.strip().lstrip('*')
                if p and p.isidentifier():
                    args.append({"name": p, "type": "number", "default": None})

        if not args:
            # Infer from common math patterns
            name_lower = name.lower()
            if name_lower in ('pow', 'log', 'fmod', 'copysign', 'hypot', 'atan2', 'ldexp'):
                args = [{"name": "x", "type": "number", "default": None},
                        {"name": "y", "type": "number", "default": None}]
            elif name_lower in ('frexp', 'modf', 'lgamma'):
                args = [{"name": "x", "type": "number", "default": None}]
            else:
                # Default: single arg
                args = [{"name": "x", "type": "number", "default": None}]

        return FunctionProfile(
            name=name,
            module=module,
            args=args,
            docstring=doc,
            category=self._categorize(name, doc, args),
        )

    def _profile_ast_function(self, node: ast.FunctionDef, module: str, source: str) -> Optional[FunctionProfile]:
        """Profile a function from AST."""
        args = []
        for arg in node.args.args:
            atype = "any"
            if arg.annotation:
                atype = self._type_map.get(self._eval_annotation(arg.annotation), "any")
            args.append({"name": arg.arg, "type": atype, "default": None})

        # Handle defaults
        defaults = node.args.defaults
        if defaults:
            for i, default in enumerate(defaults):
                arg_idx = len(args) - len(defaults) + i
                if arg_idx < len(args):
                    args[arg_idx]["default"] = self._eval_default(default)

        doc = ast.get_docstring(node) or ""
        body_lines = source.split('\n')[node.body[0].end_lineno:node.end_lineno] if hasattr(node, 'end_lineno') else []
        body_summary = ' '.join(line.strip() for line in body_lines[:3])

        return FunctionProfile(
            name=node.name,
            module=module,
            args=args,
            docstring=doc,
            body_summary=body_summary,
            category=self._categorize(node.name, doc, args),
        )

    def _eval_annotation(self, ann) -> str:
        """Simplify an AST annotation to a string."""
        if isinstance(ann, ast.Name):
            return ann.id
        if isinstance(ann, ast.Constant):
            return str(ann.value)
        return "any"

    def _eval_default(self, default) -> Any:
        """Evaluate a default value from AST."""
        if isinstance(default, ast.Constant):
            return default.value
        return None

    def _categorize(self, name: str, doc: str, args: List[dict]) -> str:
        """Categorize a function by its name and context."""
        name_lower = name.lower()
        doc_lower = doc.lower()

        # Math patterns
        math_words = ['sum', 'mean', 'average', 'median', 'min', 'max', 'abs',
                       'round', 'floor', 'ceil', 'sqrt', 'log', 'exp', 'sin',
                       'cos', 'tan', 'pow', 'gcd', 'factorial', 'comb', 'perm']
        if any(w in name_lower for w in math_words):
            return "math"

        # Data patterns
        data_words = ['sort', 'filter', 'map', 'reduce', 'count', 'group',
                       'find', 'search', 'select', 'where', 'unique', 'reverse']
        if any(w in name_lower for w in data_words):
            return "data"

        # String patterns
        string_words = ['split', 'join', 'replace', 'strip', 'upper', 'lower',
                         'format', 'encode', 'decode', 'parse']
        if any(w in name_lower for w in string_words):
            return "string"

        # Conversion
        conv_words = ['convert', 'transform', 'cast', 'to_', 'from_']
        if any(w in name_lower for w in conv_words):
            return "conversion"

        # Check/predicate
        check_words = ['is_', 'has_', 'check', 'validate', 'verify', 'test']
        if any(w in name_lower for w in check_words):
            return "predicate"

        return "general"

    def _profile_to_vocab(self, profile: FunctionProfile) -> List[Dict]:
        """Convert a function profile to vocabulary entries."""
        entries = []
        name = profile.name
        args = profile.args
        n_args = len([a for a in args if a["default"] is None])

        # Generate FLUX-ese patterns based on category
        if profile.category == "math" and n_args <= 2:
            entries.extend(self._math_vocab(profile))
        elif profile.category == "predicate":
            entries.extend(self._predicate_vocab(profile))
        elif profile.category == "data":
            entries.extend(self._data_vocab(profile))
        else:
            entries.extend(self._generic_vocab(profile))

        return entries

    def _math_vocab(self, profile: FunctionProfile) -> List[Dict]:
        """Generate vocabulary for math functions."""
        entries = []
        name = profile.name
        args = profile.args
        num_args = len(args)

        # Single-arg math: "sqrt of 16"
        if num_args == 1:
            arg = args[0]["name"]
            pattern = f"{name} of $val"
            desc = profile.docstring.split('\n')[0] if profile.docstring else f"Compute {name}"
            entries.append({
                "pattern": pattern,
                "assembly": self._wrap_native_call(profile),
                "result_reg": 0,
                "name": name,
                "description": desc,
                "tags": ["math", profile.category],
                "native_call": True,  # Flag: needs Python runtime, not bytecode
                "python_fn": f"{profile.module}.{name}",
            })

        # Two-arg math: "gcd of 12 and 8"
        elif num_args == 2:
            a, b = args[0]["name"], args[1]["name"]
            pattern = f"{name} of $a and $b"
            desc = profile.docstring.split('\n')[0] if profile.docstring else f"Compute {name}"
            entries.append({
                "pattern": pattern,
                "assembly": self._wrap_native_call(profile),
                "result_reg": 0,
                "name": name,
                "description": desc,
                "tags": ["math", profile.category],
                "native_call": True,
                "python_fn": f"{profile.module}.{name}",
            })

        # Variadic: "sum of values"
        elif num_args == 0 or (num_args == 1 and args[0]["name"] in ('values', 'args', 'iterable', 'seq', 'data')):
            pattern = f"{name} of $values"
            desc = profile.docstring.split('\n')[0] if profile.docstring else f"Compute {name}"
            entries.append({
                "pattern": pattern,
                "assembly": self._wrap_native_call(profile),
                "result_reg": 0,
                "name": name,
                "description": desc,
                "tags": ["math", "aggregation"],
                "native_call": True,
                "python_fn": f"{profile.module}.{name}",
            })

        return entries

    def _predicate_vocab(self, profile: FunctionProfile) -> List[Dict]:
        """Generate vocabulary for predicate/check functions."""
        entries = []
        name = profile.name

        # Strip is_/has_ prefix for natural patterns
        clean = name
        for prefix in ('is_', 'has_', 'check_', 'verify_'):
            if name.startswith(prefix):
                clean = name[len(prefix):]

        if profile.args:
            arg = profile.args[0]["name"]
            pattern = f"check if {clean} for $val"
            desc = profile.docstring.split('\n')[0] if profile.docstring else f"Check if {clean}"
            entries.append({
                "pattern": pattern,
                "assembly": self._wrap_native_call(profile),
                "result_reg": 13,  # R13 = comparison result
                "name": name,
                "description": desc,
                "tags": ["predicate", "check"],
                "native_call": True,
                "python_fn": f"{profile.module}.{name}",
            })

        return entries

    def _data_vocab(self, profile: FunctionProfile) -> List[Dict]:
        """Generate vocabulary for data manipulation functions."""
        entries = []
        name = profile.name

        if profile.args:
            pattern = f"{name} $data"
            desc = profile.docstring.split('\n')[0] if profile.docstring else f"Apply {name}"
            entries.append({
                "pattern": pattern,
                "assembly": self._wrap_native_call(profile),
                "result_reg": 0,
                "name": name,
                "description": desc,
                "tags": ["data", profile.category],
                "native_call": True,
                "python_fn": f"{profile.module}.{name}",
            })

        return entries

    def _generic_vocab(self, profile: FunctionProfile) -> List[Dict]:
        """Generate vocabulary for general functions."""
        entries = []
        name = profile.name

        num_args = len(profile.args)
        if num_args == 0:
            pattern = f"{name}"
        elif num_args == 1:
            pattern = f"{name} $val"
        elif num_args == 2:
            pattern = f"{name} $a and $b"
        else:
            pattern = f"{name} $args"

        desc = profile.docstring.split('\n')[0] if profile.docstring else f"Execute {name}"
        entries.append({
            "pattern": pattern,
            "assembly": self._wrap_native_call(profile),
            "result_reg": 0,
            "name": name,
            "description": desc[:200],
            "tags": [profile.category],
            "native_call": True,
            "python_fn": f"{profile.module}.{name}",
        })

        return entries

    def _wrap_native_call(self, profile: FunctionProfile) -> str:
        """
        Generate a bytecode wrapper for a native Python function call.

        For functions that can't be expressed in pure FLUX bytecode,
        we generate a stub that marks the result register and HALTs.
        The actual call is handled by the NativeBridge at runtime.
        """
        # Stub: MOVI R0, 0 (placeholder) + HALT
        # Real execution happens through the NativeBridge
        return "MOVI R0, 0\nHALT"


class NativeBridge:
    """
    Bridges FLUX vocabulary patterns to actual Python function calls.

    When the Decomposer creates vocabulary entries that can't be expressed
    in pure FLUX bytecode (like calling math.sqrt()), the NativeBridge
    handles the actual function invocation.

    Usage:
        from flux.open_interp.decomposer import Decomposer, NativeBridge

        d = Decomposer()
        vocab = d.decompose_module("math")

        bridge = NativeBridge()
        bridge.register_vocabulary(vocab)

        result = bridge.call("sqrt of 16")  # 4.0
        result = bridge.call("gcd of 12 and 8")  # 4
    """

    def __init__(self):
        self._functions: Dict[str, dict] = {}

    def register_vocabulary(self, vocab: DecomposedVocabulary):
        """Register all native-call entries from a vocabulary."""
        for entry in vocab.entries:
            if entry.get("native_call") and entry.get("python_fn"):
                self._functions[entry["name"]] = entry

    def register_module(self, module_name: str):
        """Shortcut: decompose and register a module."""
        d = Decomposer()
        vocab = d.decompose_module(module_name)
        self.register_vocabulary(vocab)
        return vocab

    def call(self, text: str) -> Any:
        """
        Execute a natural language command via native Python bridge.

        Args:
            text: Natural language command matching a registered pattern

        Returns:
            The result of the Python function call
        """
        for name, entry in self._functions.items():
            pattern = entry["pattern"]
            # Build regex from pattern
            parts = re.split(r'(\$\w+)', pattern)
            regex_parts = []
            for p in parts:
                if p.startswith('$'):
                    regex_parts.append(r'(?P<' + p[1:] + r'>[\w.,\-\s]+)')
                else:
                    regex_parts.append(re.escape(p))

            m = re.match(''.join(regex_parts), text, re.IGNORECASE)
            if m:
                fn_path = entry["python_fn"]
                args = m.groupdict()

                # Parse numeric args
                parsed = {}
                for k, v in args.items():
                    v = v.strip()
                    # Handle 'and' and ',' separated values
                    if ' and ' in v or ',' in v:
                        parts = re.split(r'\s*(?:,|and)\s*', v)
                        try:
                            parsed[k] = [float(x) if '.' in x else int(x) for x in parts if x]
                        except ValueError:
                            parsed[k] = v
                    else:
                        try:
                            # Try int first, then float
                            try:
                                parsed[k] = int(v)
                            except ValueError:
                                parsed[k] = float(v)
                        except ValueError:
                            parsed[k] = v

                # Import and call
                mod_path, fn_name = fn_path.rsplit('.', 1)
                mod = importlib.import_module(mod_path)
                fn = getattr(mod, fn_name)

                # Handle different arg shapes
                arg_values = list(parsed.values())
                
                # Check if function is variadic (*args) - flatten lists
                import inspect as _ins
                try:
                    _sig = _ins.signature(fn)
                    _variadic = any(p.kind == _ins.Parameter.VAR_POSITIONAL for p in _sig.parameters.values())
                except (ValueError, TypeError):
                    _variadic = False
                
                if _variadic:
                    # Flatten all args into a single list
                    flat = []
                    for v in arg_values:
                        if isinstance(v, list):
                            flat.extend(v)
                        else:
                            flat.append(v)
                    return fn(*flat)
                
                # Variadic: single list arg
                if len(arg_values) == 1 and isinstance(arg_values[0], list):
                    return fn(*arg_values[0])
                
                return fn(*arg_values)

        raise ValueError(f"No matching function for: {text}")

    def list_functions(self) -> List[str]:
        """List all registered functions with their patterns."""
        return [f"{e['pattern']:40s} → {e['python_fn']}" for e in self._functions.values()]

    def decompose_and_run(self, module_name: str, text: str) -> Any:
        """One-shot: decompose module and execute command."""
        self.register_module(module_name)
        return self.call(text)
