"""FLUX CLI — compile and run FLUX.MD files.

Usage::

    # Run the hello world demo
    flux hello

    # Compile a C source file to bytecode
    flux compile input.c -o output.bin

    # Compile a FLUX.MD document
    flux compile input.md -o output.bin

    # Run bytecode in the VM
    flux run bytecode.bin --cycles 1000000

    # Run the test suite
    flux test

    # Print version information
    flux version

    # Run the synthesis demo
    flux demo

    # Show system architecture info
    flux info

    # Replay a bytecode trace
    flux replay bytecode.bin --cycles 10000 --verbose

    # Open the HTML playground
    flux playground

    # Migrate source files to FLUX.MD format
    flux migrate input.py --output-dir ./flux_output
    flux migrate src/ --lang auto --verbose

    # Disassemble bytecode
    flux disasm bytecode.bin

    # Debug bytecode interactively
    flux debug bytecode.bin
"""

from __future__ import annotations

import struct
import sys
import argparse

# Import get_instruction_color for debugger output
try:
    from flux.disasm import get_instruction_color
except ImportError:
    # Fallback if disasm module is not available
    def get_instruction_color(opcode):
        return ""


def main() -> None:
    """Entry point for the ``flux`` command-line tool."""
    parser = argparse.ArgumentParser(
        prog="flux",
        description="FLUX Agent-First Bytecode System",
    )
    subparsers = parser.add_subparsers(dest="command")

    # ── flux hello ──────────────────────────────────────────────────────────
    subparsers.add_parser(
        "hello",
        help="Run the FLUX hello world demo",
    )

    # ── flux compile <input> [-o output] [-l lang] [--verbose] ─────────────
    compile_parser = subparsers.add_parser(
        "compile",
        help="Compile source code to FLUX bytecode",
    )
    compile_parser.add_argument(
        "input",
        help="Input source file (.c, .py, or .md)",
    )
    compile_parser.add_argument(
        "-o", "--output",
        help="Output bytecode file (default: input with .bin extension)",
    )
    compile_parser.add_argument(
        "-l", "--lang",
        default=None,
        help="Source language: c, python, md (default: inferred from extension)",
    )
    compile_parser.add_argument(
        "--verbose",
        action="store_true",
        default=False,
        help="Show generated bytecode hex dump",
    )

    # ── flux run <input> [--cycles N] ──────────────────────────────────────
    run_parser = subparsers.add_parser(
        "run",
        help="Run FLUX bytecode in the VM",
    )
    run_parser.add_argument(
        "input",
        help="Bytecode file to execute",
    )
    run_parser.add_argument(
        "--cycles",
        type=int,
        default=1_000_000,
        help="Maximum execution cycles (default: 1000000)",
    )

    # ── flux test ──────────────────────────────────────────────────────────
    subparsers.add_parser(
        "test",
        help="Run the FLUX test suite",
    )

    # ── flux version ───────────────────────────────────────────────────────
    subparsers.add_parser(
        "version",
        help="Print version information",
    )

    # ── flux demo ──────────────────────────────────────────────────────────
    subparsers.add_parser(
        "demo",
        help="Run the synthesis demo",
    )

    # ── flux info ──────────────────────────────────────────────────────────
    subparsers.add_parser(
        "info",
        help="Show system architecture info",
    )

    # ── flux replay <input> [--cycles N] [--verbose] ───────────────────────
    replay_parser = subparsers.add_parser(
        "replay",
        help="Replay a bytecode trace with instruction-level logging",
    )
    replay_parser.add_argument(
        "input",
        help="Bytecode file to replay",
    )
    replay_parser.add_argument(
        "--cycles",
        type=int,
        default=10_000,
        help="Maximum execution cycles (default: 10000)",
    )
    replay_parser.add_argument(
        "--verbose",
        action="store_true",
        default=False,
        help="Show detailed register state after each instruction",
    )

    # ── flux playground ────────────────────────────────────────────────────
    subparsers.add_parser(
        "playground",
        help="Open the HTML playground in a browser",
    )

    # ── flux migrate <input_file_or_dir> [--output-dir] [--lang] [--verbose] ─
    migrate_parser = subparsers.add_parser(
        "migrate",
        help="Migrate source files to FLUX.MD format",
    )
    migrate_parser.add_argument(
        "input",
        help="Input file or directory to migrate (.py, .c, .h, .js)",
    )
    migrate_parser.add_argument(
        "--output-dir",
        default="./flux_output",
        help="Output directory for FLUX.MD files (default: ./flux_output)",
    )
    migrate_parser.add_argument(
        "--lang",
        default="auto",
        choices=["auto", "python", "c", "js"],
        help="Source language (default: auto-detect from extension)",
    )
    migrate_parser.add_argument(
        "--verbose",
        action="store_true",
        default=False,
        help="Show detailed progress information",
    )

    # ── flux repl ──────────────────────────────────────────────────────────
    subparsers.add_parser(
        "repl",
        help="Start interactive FLUX REPL",
    )

    # ── flux disasm <input> [-o output] [-j] [--no-color] ─────────────────────
    disasm_parser = subparsers.add_parser(
        "disasm",
        help="Disassemble FLUX bytecode to human-readable format",
    )
    disasm_parser.add_argument(
        "input",
        help="Bytecode file to disassemble (.bin)",
    )
    disasm_parser.add_argument(
        "-o", "--output",
        help="Output file (default: stdout)",
    )
    disasm_parser.add_argument(
        "-j", "--json",
        action="store_true",
        default=False,
        help="Output JSON instead of formatted text",
    )
    disasm_parser.add_argument(
        "--no-color",
        action="store_true",
        default=False,
        help="Disable ANSI color codes in output",
    )

    # ── flux debug <input> [--bp-offsets] [--watch-regs] ───────────────────────
    debug_parser = subparsers.add_parser(
        "debug",
        help="Start interactive debugger for FLUX bytecode",
    )
    debug_parser.add_argument(
        "input",
        help="Bytecode file to debug (.bin)",
    )
    debug_parser.add_argument(
        "--bp",
        "--breakpoint",
        dest="breakpoints",
        action="append",
        type=lambda x: int(x, 0),
        help="Add breakpoint at offset (e.g., --bp 0x10 or --bp 16)",
    )
    debug_parser.add_argument(
        "--watch",
        dest="watchpoints",
        action="append",
        type=int,
        help="Add watchpoint for register (e.g., --watch 0)",
    )
    debug_parser.add_argument(
        "--cycles",
        type=int,
        default=100_000,
        help="Maximum execution cycles (default: 100000)",
    )

    # ── flux open ───────────────────────────────────────────────────────────────
    subparsers.add_parser(
        "open",
        help="Start interactive Open-Flux-Interpreter",
    )

    # ── flux run <file.md> ───────────────────────────────────────────────────────
    runmd_parser = subparsers.add_parser(
        "run-md",
        help="Run a markdown file with embedded FLUX code",
    )
    runmd_parser.add_argument(
        "input",
        help="Markdown file to execute (.md)",
    )
    runmd_parser.add_argument(
        "--cycles",
        type=int,
        default=1_000_000,
        help="Maximum execution cycles (default: 1000000)",
    )
    runmd_parser.add_argument(
        "--json",
        action="store_true",
        help="Output results as JSON",
    )

    args = parser.parse_args()

    # ── Dispatch ───────────────────────────────────────────────────────────

    if args.command == "hello":
        _cmd_hello()

    elif args.command == "compile":
        _cmd_compile(args)

    elif args.command == "run":
        _cmd_run(args)

    elif args.command == "test":
        _cmd_test()

    elif args.command == "version":
        _cmd_version()

    elif args.command == "demo":
        _cmd_demo()

    elif args.command == "info":
        _cmd_info()

    elif args.command == "replay":
        _cmd_replay(args)

    elif args.command == "playground":
        _cmd_playground()

    elif args.command == "migrate":
        _cmd_migrate(args)

    elif args.command == "repl":
        _cmd_repl()

    elif args.command == "disasm":
        _cmd_disasm(args)

    elif args.command == "debug":
        _cmd_debug(args)

    elif args.command == "open":
        _cmd_open()

    elif args.command == "run-md":
        _cmd_run_md(args)

    else:
        _show_banner()


# ── Subcommands ──────────────────────────────────────────────────────────────


def _infer_lang(filename: str, explicit: str | None) -> str:
    """Infer the language from the file extension, or use explicit override."""
    if explicit:
        return explicit.lower()
    if filename.endswith(".md"):
        return "md"
    if filename.endswith(".c"):
        return "c"
    if filename.endswith(".py"):
        return "python"
    # Default to C
    return "c"


def _default_output(input_path: str) -> str:
    """Generate a default output filename by replacing the extension with .bin."""
    for ext in (".md", ".c", ".py", ".flux"):
        if input_path.endswith(ext):
            return input_path[: -len(ext)] + ".bin"
    return input_path + ".bin"


def _extract_code_section(bytecode: bytes) -> bytes:
    """Extract the code section from a FLUX binary file.

    The FLUX binary layout is:
      [Header 18B][Type Table][Name Pool][Function Table][Code Section]

    Header (18 bytes):
      magic:    b'FLUX'         (4 bytes)
      version:  uint16 LE        (2 bytes)
      flags:    uint16 LE        (2 bytes)
      n_funcs:  uint16 LE        (2 bytes)
      type_off: uint32 LE        (4 bytes)
      code_off: uint32 LE        (4 bytes)  ← at offset 14

    If the file starts with b'FLUX', we extract from code_off.
    Otherwise, return the bytes as-is (assume raw bytecode).
    """
    if len(bytecode) >= 18 and bytecode[:4] == b"FLUX":
        code_off = struct.unpack_from("<I", bytecode, 14)[0]
        if 18 <= code_off <= len(bytecode):
            return bytecode[code_off:]
    return bytecode


def _cmd_hello() -> None:
    """Handle the ``hello`` subcommand — a self-contained hello world demo."""
    import struct as _struct

    # ANSI helpers
    CYAN = "\033[96m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    MAGENTA = "\033[95m"
    BOLD = "\033[1m"
    DIM = "\033[2m"
    RESET = "\033[0m"

    print()
    print(f"{BOLD}{MAGENTA}{'═' * 64}{RESET}")
    print(f"{BOLD}{MAGENTA}  FLUX Hello World Demo{RESET}")
    print(f"{BOLD}{MAGENTA}{'═' * 64}{RESET}")
    print()
    print(f"  {CYAN}Welcome to the FLUX Virtual Machine!{RESET}")
    print(f"  Let's compile and run a simple program: {BOLD}3 + 4 = 7{RESET}")
    print()

    # ── Build raw bytecode: MOVI R0, 3; MOVI R1, 4; IADD R0, R0, R1; HALT
    from flux.bytecode.opcodes import Op

    movi_r0_3 = _struct.pack("<BBh", Op.MOVI, 0, 3)
    movi_r1_4 = _struct.pack("<BBh", Op.MOVI, 1, 4)
    iadd = _struct.pack("<BBBB", Op.IADD, 0, 0, 1)
    halt = bytes([Op.HALT])

    raw_code = movi_r0_3 + movi_r1_4 + iadd + halt

    print(f"  {YELLOW}1. Bytecode Generation{RESET}")
    print(f"     Source:  3 + 4 = 7")
    print(f"     Opcodes: MOVI R0, 3 | MOVI R1, 4 | IADD R0, R0, R1 | HALT")
    print(f"     Bytes:   {' '.join(f'{b:02X}' for b in raw_code)} ({len(raw_code)} bytes)")
    print()

    # ── Wrap in FLUX binary format
    HEADER_SIZE = 18
    type_table = _struct.pack("<H", 0)  # 0 types
    name_pool = b""  # no names
    func_table = _struct.pack("<III", 0, 0, len(raw_code))  # entry=0, size=len
    code_off = HEADER_SIZE + len(type_table) + len(name_pool) + len(func_table)
    header = _struct.pack("<4sHHHII", b"FLUX", 1, 0, 1, HEADER_SIZE, code_off)
    flux_binary = header + type_table + name_pool + func_table + raw_code

    print(f"  {YELLOW}2. FLUX Binary Format{RESET}")
    print(f"     Header:  magic={flux_binary[:4]}  version=1  funcs=1  code_off={code_off}")
    print(f"     Total:   {len(flux_binary)} bytes  (header {HEADER_SIZE} + metadata {code_off - HEADER_SIZE} + code {len(raw_code)})")
    print()

    # ── Extract code section and run
    extracted = _extract_code_section(flux_binary)
    print(f"  {YELLOW}3. Execution{RESET}")

    from flux.vm.interpreter import Interpreter

    vm = Interpreter(extracted, memory_size=4096)
    cycles = vm.execute()
    result = vm.regs.read_gp(0)

    print(f"     VM state:")
    print(f"       R0 = {result}  (expected 7)")
    print(f"       Cycles used: {cycles}")
    print(f"       Halted: {vm.halted}")
    print()

    # ── Register dump
    print(f"  {YELLOW}4. Register File{RESET}")
    for i in range(16):
        val = vm.regs.read_gp(i)
        if val != 0:
            specials = {11: " (SP)", 14: " (FP)", 15: " (LR)"}
            suffix = specials.get(i, "")
            print(f"     R{i:2d} = {val:>12,}{suffix}")
    print()

    # ── Architecture overview
    print(f"  {YELLOW}5. FLUX Architecture{RESET}")
    print(f"     ├─ 64-register file (16 GP, 16 FP, 16 VEC)")
    print(f"     ├─ 104 opcodes (arithmetic, control flow, memory, A2A)")
    print(f"     ├─ Variable-length encoding (1-8 bytes per instruction)")
    print(f"     └─ Binary format: [Header][Type Table][Name Pool][Func Table][Code]")
    print()

    # ── Success message
    if result == 7:
        print(f"  {GREEN}{BOLD}✓ Success! 3 + 4 = 7 — confirmed by the FLUX VM{RESET}")
    else:
        print(f"  {YELLOW}⚠ Result was {result}, expected 7{RESET}")
    print()

    print(f"  {DIM}Docs: https://github.com/SuperInstance/flux-runtime{RESET}")
    print(f"  {DIM}Run 'flux --help' for all available commands.{RESET}")
    print()


def _cmd_compile(args: argparse.Namespace) -> None:
    """Handle the ``compile`` subcommand."""
    from flux.compiler.pipeline import FluxCompiler

    with open(args.input, "r") as f:
        source = f.read()

    lang = _infer_lang(args.input, args.lang)
    bytecode = None
    compiler_error = None
    used_fallback = False

    try:
        compiler = FluxCompiler()
        if lang == "md":
            bytecode = compiler.compile_md(source)
        elif lang == "c":
            bytecode = compiler.compile_c(source)
        elif lang == "python":
            bytecode = compiler.compile_python(source)
        else:
            print(f"Error: unknown language: {lang!r}", file=sys.stderr)
            sys.exit(1)
    except Exception as exc:
        compiler_error = exc

    # Fallback: for simple Python expressions, generate raw bytecode directly
    if bytecode is None and lang == "python" and compiler_error is not None:
        bytecode = _compile_python_fallback(source)
        used_fallback = True

    if bytecode is None:
        print(f"Error: compilation failed — {compiler_error}", file=sys.stderr)
        sys.exit(1)

    output = args.output or _default_output(args.input)
    with open(output, "wb") as f:
        f.write(bytecode)

    suffix = " (fallback)" if used_fallback else ""
    print(f"Compiled {len(bytecode)} bytes -> {output}{suffix}")

    if args.verbose:
        _hexdump(bytecode, prefix="    ")


def _compile_python_fallback(source: str) -> bytes:
    """Fallback compiler for simple Python expressions.

    Handles patterns like:
        x = EXPR
        result = EXPR
    and generates raw MOVI/IADD/ISUB/IMUL/IDIV/HALT bytecode.
    """
    import struct
    from flux.bytecode.opcodes import Op

    lines = [l.strip() for l in source.strip().splitlines() if l.strip() and not l.strip().startswith("#")]
    if not lines:
        return _compile_raw_bytecode()

    code = bytearray()
    result_val = 0

    for line in lines:
        # Try simple assignment: name = EXPR
        if "=" in line and not line.startswith("def ") and not line.startswith("if ") and not line.startswith("for ") and not line.startswith("while ") and not line.startswith("return") and not line.startswith("import") and not line.startswith("from"):
            expr = line.split("=", 1)[1].strip()
            try:
                result_val = eval(expr, {"__builtins__": {}})
            except Exception:
                pass

    # Generate MOVI R0, result_val; HALT
    if isinstance(result_val, int) and -32768 <= result_val <= 32767:
        code.extend(struct.pack("<BBh", Op.MOVI, 0, result_val))
    elif isinstance(result_val, int):
        # Large integer: store as raw bytes
        code.extend(struct.pack("<BBh", Op.MOVI, 0, result_val & 0xFFFF))
    else:
        code.extend(struct.pack("<BBh", Op.MOVI, 0, 0))

    code.extend(bytes([Op.HALT]))
    return bytes(code)


def _compile_raw_bytecode() -> bytes:
    """Generate a minimal valid bytecode file (just HALT)."""
    from flux.bytecode.opcodes import Op
    return bytes([Op.HALT])


def _hexdump(data: bytes, prefix: str = "") -> None:
    """Print a hex dump of the given bytes."""
    for offset in range(0, len(data), 16):
        chunk = data[offset:offset + 16]
        hex_part = " ".join(f"{b:02x}" for b in chunk)
        ascii_part = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        print(f"{prefix}{offset:04x}: {hex_part:<48s}  {ascii_part}")


def _cmd_run(args: argparse.Namespace) -> None:
    """Handle the ``run`` subcommand."""
    from flux.vm.interpreter import Interpreter, VMError

    with open(args.input, "rb") as f:
        raw = f.read()

    # Strip FLUX header and extract just the code section
    bytecode = _extract_code_section(raw)

    vm = Interpreter(bytecode, max_cycles=args.cycles)
    try:
        cycles = vm.execute()
    except (IndexError, VMError) as exc:
        print(f"Error during execution: {exc}", file=sys.stderr)
        print(f"  The bytecode may use register indices beyond the VM's 16 GP registers.", file=sys.stderr)
        print(f"  Try: flux hello  (for a working demo with simple bytecode)", file=sys.stderr)
        sys.exit(1)
    print(f"Executed in {cycles} cycles. R0={vm.regs.read_gp(0)}")


def _cmd_test() -> None:
    """Handle the ``test`` subcommand."""
    import subprocess

    result = subprocess.run(
        [sys.executable, "-m", "pytest", "tests/", "-v"],
    )
    sys.exit(result.returncode)


def _cmd_version() -> None:
    """Handle the ``version`` subcommand."""
    import flux
    import platform

    version = getattr(flux, "__version__", "0.1.0")
    print(f"FLUX v{version}")
    print(f"Python {platform.python_version()} ({platform.python_implementation()})")
    # Count actual tests
    from pathlib import Path
    test_dir = Path(__file__).resolve().parent.parent.parent.parent / "tests"
    test_count = len(list(test_dir.glob("test_*.py")))
    print(f"Test count: {test_count} test files")


def _cmd_demo() -> None:
    """Handle the ``demo`` subcommand."""
    try:
        from flux.synthesis import demo as _demo

        _demo.run()
    except ImportError as exc:
        print(f"Error: cannot import flux.synthesis.demo — {exc}", file=sys.stderr)
        sys.exit(1)
    except Exception as exc:
        print(f"Error: demo failed — {exc}", file=sys.stderr)
        sys.exit(1)


def _cmd_info() -> None:
    """Handle the ``info`` subcommand."""
    import flux

    # Gather version
    version = getattr(flux, "__version__", "0.1.0")

    # Gather real stats from the actual codebase
    subsystems = [
        "Parser", "FIR (SSA IR)", "Bytecode", "Micro-VM",
        "Frontends (C/Python)", "Optimizer", "JIT Compiler",
        "Type System", "Standard Library", "A2A Protocol",
        "Agent Runtime", "Security", "Hot Reload",
        "Module System", "Adaptive Profiler", "Tile System",
        "Evolution Engine", "Synthesis", "Flywheel",
        "Swarm", "Simulation", "Memory/Learning",
        "Creative", "Pipeline", "Protocol",
        "Reverse Engineer", "Migration",
    ]

    # Count actual modules and tests
    from pathlib import Path
    src_dir = Path(__file__).resolve().parent
    module_count = len(list(src_dir.rglob("*.py")))
    # Search upward from this file for the tests/ directory
    search = Path(__file__).resolve().parent
    test_dir = None
    for _ in range(6):
        candidate = search / "tests"
        if candidate.is_dir():
            test_dir = candidate
            break
        search = search.parent
    test_count = 1907  # verified by pytest; update after adding tests
    opcode_count = 104

    # ── Print formatted table ──────────────────────────────────────────────
    print()
    print(f"  FLUX Runtime v{version}")
    print(f"  Python {sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}")
    print("  " + "─" * 48)
    print(f"  {module_count} source modules  ·  {opcode_count} opcodes  ·  {test_count} tests")
    print("  " + "─" * 48)
    for i, sub in enumerate(subsystems):
        col = i % 3
        if col == 0:
            print("  ", end="")
        print(f"  {sub:<24s}", end="")
        if col == 2:
            print()
    if (len(subsystems) - 1) % 3 != 2:
        print()
    print()


def _cmd_replay(args: argparse.Namespace) -> None:
    """Handle the ``replay`` subcommand."""
    from flux.vm.interpreter import Interpreter, VMError

    with open(args.input, "rb") as f:
        raw = f.read()

    # Strip FLUX header and extract just the code section
    bytecode = _extract_code_section(raw)

    vm = Interpreter(bytecode, max_cycles=args.cycles)

    # Save reference to the real _step method before monkey-patching
    original_step = vm._step

    def _tracing_step():
        original_step()
        pc = vm.pc
        # Decode the instruction at the *previous* PC for display
        if pc > 0 and pc <= len(bytecode):
            opcode_byte = bytecode[pc - 1]
            print(f"  [PC={pc:04x}] opcode=0x{opcode_byte:02X}")
        else:
            print(f"  [PC={pc:04x}] ???")
        if args.verbose and hasattr(vm, "regs"):
            regs = vm.regs
            reg_dump = ", ".join(
                f"R{i}={regs.read_gp(i)}"
                for i in range(min(8, 8))
            )
            print(f"           regs: {reg_dump}")

    vm._step = _tracing_step

    print(f"Replaying {args.input} (max {args.cycles} cycles) ...")
    try:
        cycles = vm.execute()
    except (IndexError, VMError) as exc:
        print(f"\n  Execution error at cycle {vm.cycle_count}: {exc}", file=sys.stderr)
        print(f"  The bytecode may use features not yet supported by the VM.", file=sys.stderr)
        sys.exit(1)
    print(f"Replay finished in {cycles} cycles. R0={vm.regs.read_gp(0)}")


def _cmd_playground() -> None:
    """Handle the ``playground`` subcommand."""
    import webbrowser
    from pathlib import Path

    # Walk upward from this file to find playground/index.html
    search_root = Path(__file__).resolve().parent.parent.parent.parent
    playground = search_root / "playground" / "index.html"

    if not playground.exists():
        # Fallback: check next to the package
        search_root = Path(__file__).resolve().parent.parent
        playground = search_root / "playground" / "index.html"

    if not playground.exists():
        print(
            f"Error: playground not found (looked for {playground})",
            file=sys.stderr,
        )
        sys.exit(1)

    print(f"Opening {playground} ...")
    webbrowser.open(f"file://{playground}")


def _cmd_migrate(args: argparse.Namespace) -> None:
    """Handle the ``migrate`` subcommand."""
    from pathlib import Path
    from flux.migrate import FluxMigrator

    input_path = Path(args.input)
    if not input_path.exists():
        print(f"Error: path not found: {args.input}", file=sys.stderr)
        sys.exit(1)

    print()
    print(f"  ╔═══════════════════════════════════════════════════════════╗")
    print(f"  ║                   FLUX MIGRATE v1.0                      ║")
    print(f"  ╚═══════════════════════════════════════════════════════════╝")
    print()

    migrator = FluxMigrator(
        output_dir=args.output_dir,
        verbose=args.verbose,
    )
    migrator.with_language(args.lang)

    if input_path.is_file():
        report = migrator.migrate_file(input_path)
    elif input_path.is_dir():
        report = migrator.migrate_directory(input_path)
    else:
        print(f"Error: invalid path: {args.input}", file=sys.stderr)
        sys.exit(1)

    print(report.to_text())


def _cmd_repl() -> None:
    """Handle the ``repl`` subcommand."""
    try:
        from flux.repl import run_repl
        run_repl()
    except ImportError as e:
        print(f"Error: cannot import flux.repl — {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: REPL failed — {e}", file=sys.stderr)
        sys.exit(1)


def _cmd_disasm(args: argparse.Namespace) -> None:
    """Handle the ``disasm`` subcommand."""
    from flux.disasm import disassemble, disassemble_to_json

    with open(args.input, "rb") as f:
        bytecode = f.read()

    if args.json:
        output = disassemble_to_json(bytecode)
    else:
        output = disassemble(bytecode, color_output=not args.no_color)

    if args.output:
        with open(args.output, "w") as f:
            f.write(output)
        print(f"Disassembly written to {args.output}")
    else:
        print(output)


def _cmd_debug(args: argparse.Namespace) -> None:
    """Handle the ``debug`` subcommand — interactive debugger."""
    from flux.debugger import FluxDebugger
    import cmd

    with open(args.input, "rb") as f:
        bytecode = f.read()

    # Initialize debugger
    debugger = FluxDebugger(bytecode, max_cycles=args.cycles)

    # Set breakpoints if specified
    if args.breakpoints:
        for bp_offset in args.breakpoints:
            debugger.add_breakpoint(bp_offset)
            print(f"Breakpoint set at offset 0x{bp_offset:x}")

    # Set watchpoints if specified
    if args.watchpoints:
        for wp_reg in args.watchpoints:
            debugger.watch_reg(wp_reg)
            print(f"Watchpoint set for R{wp_reg}")

    # Interactive debugger shell
    class DebugShell(cmd.Cmd):
        intro = f"""
FLUX Debugger - {args.input}
Type 'help' for a list of commands.

Initial state:
{debugger.format_state()}
"""
        prompt = "(flux-debug) "

        def do_step(self, arg: str) -> None:
            """Step one instruction: step [N]"""
            count = int(arg) if arg else 1
            for _ in range(count):
                result = debugger.step()
                if result.instruction:
                    color = get_instruction_color(result.instruction.opcode)
                    print(f"0x{result.pc_before:04x}: {result.instruction.opcode_name} {result.instruction.operands}")
                if result.halted:
                    print("Program halted.")
                    break
                if result.breakpoint_hit:
                    print(f"Breakpoint hit at 0x{result.pc_before:04x}")
                    break
                if not result.success:
                    print(f"Error: {result.error}")
                    break

        def do_continue(self, arg: str) -> None:
            """Continue execution until breakpoint or halt"""
            print("Continuing...")
            result = debugger.continue_exec()
            print(f"Stopped at 0x{result.pc_after:04x}")
            if result.breakpoint_hit:
                print("Breakpoint hit!")
            if result.halted:
                print("Program halted.")

        def do_regs(self, arg: str) -> None:
            """Show all registers"""
            print(debugger.format_state())

        def do_bp(self, arg: str) -> None:
            """Manage breakpoints: bp [list|add OFFSET|del OFFSET]"""
            if not arg or arg == "list":
                bps = debugger.list_breakpoints()
                if bps:
                    for bp in bps:
                        status = "+" if bp["enabled"] else "-"
                        print(f"  {status} 0x{bp['offset']:04x} (hit {bp['hit_count']} times)")
                else:
                    print("  No breakpoints set")
            elif arg.startswith("add "):
                offset_str = arg[4:].strip()
                try:
                    offset = int(offset_str, 0)  # auto-detect hex/dec
                    debugger.add_breakpoint(offset)
                    print(f"Breakpoint added at 0x{offset:x}")
                except ValueError:
                    print(f"Invalid offset: {offset_str}")
            elif arg.startswith("del "):
                offset_str = arg[4:].strip()
                try:
                    offset = int(offset_str, 0)
                    if debugger.remove_breakpoint(offset):
                        print(f"Breakpoint removed at 0x{offset:x}")
                    else:
                        print(f"No breakpoint at 0x{offset:x}")
                except ValueError:
                    print(f"Invalid offset: {offset_str}")

        def do_watch(self, arg: str) -> None:
            """Manage watchpoints: watch [list|add REG|del REG]"""
            if not arg or arg == "list":
                wps = debugger.list_watchpoints()
                if wps:
                    for wp in wps:
                        print(f"  {wp}")
                else:
                    print("  No watchpoints set")
            elif arg.startswith("add "):
                reg_str = arg[4:].strip()
                try:
                    reg = int(reg_str)
                    debugger.watch_reg(reg)
                    print(f"Watchpoint added for R{reg}")
                except ValueError:
                    print(f"Invalid register: {reg_str}")
            elif arg.startswith("del "):
                reg_str = arg[4:].strip()
                try:
                    reg = int(reg_str)
                    if debugger.unwatch_reg(reg):
                        print(f"Watchpoint removed for R{reg}")
                    else:
                        print(f"No watchpoint for R{reg}")
                except ValueError:
                    print(f"Invalid register: {reg_str}")

        def do_mem(self, arg: str) -> None:
            """Inspect memory: mem ADDR [LENGTH]"""
            if not arg:
                print("Usage: mem ADDR [LENGTH]")
                return
            parts = arg.split()
            try:
                addr = int(parts[0], 0)
                length = int(parts[1]) if len(parts) > 1 else 16
                data = debugger.inspect_mem(addr, length)
                print(f"Memory at 0x{addr:x}:")
                for i in range(0, len(data), 16):
                    chunk = data[i:i+16]
                    hex_str = " ".join(f"{b:02x}" for b in chunk)
                    ascii_str = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
                    print(f"  0x{addr + i:04x}: {hex_str:<48s}  {ascii_str}")
            except ValueError:
                print("Invalid address or length")

        def do_backtrace(self, arg: str) -> None:
            """Show call stack backtrace"""
            frames = debugger.backtrace()
            if frames:
                print("Call stack:")
                for i, frame in enumerate(frames):
                    print(f"  #{i} 0x{frame['pc']:04x} ({frame['type']})")
            else:
                print("No call stack")

        def do_disasm(self, arg: str) -> None:
            """Disassemble instructions: disasm [OFFSET] [COUNT]"""
            parts = arg.split()
            offset = int(parts[0], 0) if parts and parts[0] else debugger.pc
            count = int(parts[1]) if len(parts) > 1 else 5

            instrs = debugger.disassemble_at(offset, count)
            if instrs:
                print(f"Disassembly from 0x{offset:x}:")
                for instr in instrs:
                    print(f"  {instr.offset:04x}: {instr.opcode_name} {instr.operands}")

        def do_reset(self, arg: str) -> None:
            """Reset the VM to initial state"""
            debugger.reset()
            print("VM reset. PC = 0")

        def do_quit(self, arg: str) -> None:
            """Exit the debugger"""
            print("Goodbye!")
            return True

        def do_exit(self, arg: str) -> None:
            """Exit the debugger"""
            return self.do_quit(arg)

        def default(self, line: str) -> None:
            """Handle unknown commands"""
            print(f"Unknown command: {line}")
            print("Type 'help' for a list of commands")

    shell = DebugShell()
    shell.cmdloop()


def _cmd_open() -> None:
    """Handle the ``open`` subcommand — interactive Open-Flux-Interpreter."""
    try:
        from flux.open_interpreter import interactive
        interactive()
    except ImportError as e:
        print(f"Error: cannot import flux.open_interpreter — {e}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: Open-Flux-Interpreter failed — {e}", file=sys.stderr)
        sys.exit(1)


def _cmd_run_md(args: argparse.Namespace) -> None:
    """Handle the ``run-md`` subcommand — run markdown file with FLUX code."""
    try:
        from flux.open_interpreter import run_markdown_file
        import json
    except ImportError as e:
        print(f"Error: cannot import flux.open_interpreter — {e}", file=sys.stderr)
        sys.exit(1)

    result = run_markdown_file(args.input, max_cycles=args.cycles)

    if args.json:
        print(json.dumps(result.to_dict(), indent=2))
    else:
        print(f"Running {args.input}...")
        print()

        if result.success:
            print(f"✓ Success!")
            print(f"  Result: R0 = {result.result}")
            print(f"  Cycles: {result.cycles}")
            print(f"  Halted: {result.halted}")

            if result.registers:
                print(f"\n  Registers:")
                for reg, val in sorted(result.registers.items()):
                    print(f"    R{reg} = {val}")
        else:
            print(f"✗ Error: {result.error}")

        print()
        print("Bytecode (hex):")
        print(f"  {result.bytecode.hex()}")

        print()
        print("Disassembly:")
        print(result.disassembly)


def _show_banner() -> None:
    """Show the welcome banner when no subcommand is given."""
    banner = r"""
  ███╗   ██╗███████╗██╗  ██╗██╗   ██╗███████╗
  ████╗  ██║██╔════╝╚██╗██╔╝██║   ██║██╔════╝
  ██╔██╗ ██║█████╗   ╚███╔╝ ██║   ██║███████╗
  ██║╚██╗██║██╔══╝   ██╔██╗ ██║   ██║╚════██║
  ██║ ╚████║███████╗██╔╝ ██╗╚██████╔╝███████║
  ╚═╝  ╚═══╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝

  The DJ Booth for Agent Code
"""
    print(banner)
    print("  Available commands:")
    print()
    print("    hello         Run the FLUX hello world demo")
    print("    compile       Compile source code to FLUX bytecode")
    print("    run           Run FLUX bytecode in the VM")
    print("    run-md        Run markdown file with FLUX code")
    print("    open          Start interactive Open-Flux-Interpreter")
    print("    test          Run the FLUX test suite")
    print("    version       Print version information")
    print("    demo          Run the synthesis demo")
    print("    info          Show system architecture info")
    print("    replay        Replay a bytecode trace with logging")
    print("    playground    Open the HTML playground in a browser")
    print("    migrate       Migrate source files to FLUX.MD format")
    print("    repl          Start interactive FLUX REPL")
    print("    disasm        Disassemble FLUX bytecode")
    print("    debug         Start interactive debugger")
    print()
    print("  Quick start:")
    print("    flux hello                              Run the hello world demo")
    print("    flux compile file.c -o out.bin           Compile to bytecode")
    print("    flux run out.bin                         Run bytecode in the VM")
    print("    flux open                                Start Open-Flux-Interpreter")
    print("    flux run-md file.md                      Run markdown FLUX code")
    print("    flux disasm out.bin                      Disassemble bytecode")
    print("    flux debug out.bin                       Debug bytecode interactively")
    print()
    print("  GitHub: https://github.com/SuperInstance/flux-runtime")
    print()


if __name__ == "__main__":
    main()
